# Documenté dans App\DependencyInjection\Configuration
app:
  jour: 6
  seuil_alert_animateur: 6
  seuil_anim_ok: 7
  equilibrage_pourcent_par_groupe: 0.4
  decoupage_permanence:
    groupe1:
      name: "1er groupe"
      horaire: "9h à 9h45"
    groupe2:
      name: "2ème groupe"
      horaire: "9h45 à 10h30"
    groupe3:
      name: "3ème groupe"
      horaire: "10h30 à 11h15"
    groupe4:
      name: "4ème groupe"
      horaire: "11h15 à 12h"