easy_admin:
    site_name: 'Configuration Permanences'
    entities:
#        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
        Group:
            class: App\Entity\Group
            label: 'Groupes'
            list:
                fields:
                    - { property: 'nom' }
            form:
                fields:
                    - { property: 'nom' }
        AffectUser:
            class: App\Entity\User
            label: 'Animateurs réguliers / Groupes'
            disabled_actions: ['new']
            list:
                dql_filter: 'entity.anim_regulier = 1'
                fields:
                    - { property: 'nom' }
                    - { property: 'mail' }
                    - { property: 'anim_group' }
            form:
                fields:
                    - { property: 'nom', type_options: { disabled: true }}
                    - { property: 'mail', type_options: { disabled: true } }
                    - { property: 'anim_group' }
        Permanence:
            class: App\Entity\Permanence
            label: 'Permanences'
            list:
                fields:
                    - { property: 'date' }
                    - { property: 'group_permanence' }
            form:
                fields:
                    - { property: 'date', type: 'App\Form\DatePickerType' }
                    - { property: 'group_permanence' }





